### ISSUE TITLE
Wouldn't partials be better than virtual methods?

### ISSUE THREAD

**Issue by aaronshaf** [gsklee/bound-native-methods#3]
Compare:

``` javascript
// ES7

getPlayers()::map(x => x.character())

// ES6

let _val
_val = getPlayers()
_val = map.call(_val, x => x.character())
```

 With:

``` javascript
// ES7

getPlayers()::map(x => x.character())

// ES6

let _val
_val = getPlayers()
_val = map(_val, x => x.character())
```

**Comment by aaronshaf** [comment]
I may not have phrased my proposal correctly, but consider that with lodash I could:

``` javascript
import {flatten, zip, takeWhile} from 'lodash/arrays'

let stuff = [...]
stuff::zip()::flatten()::takeWhile({'active': false})
```

Bound virtual methods assumes we want to be using context, this, etc. My proposal is perhaps more "functional"?

Perhaps there is more convenience in chaining utility functions than reusing prototype methods?

**Comment by zenparsing** [comment]
@aaronshaf some people feel that using "this" as a general-purpose parameter is...icky.  So I definitely understand where you're coming from.

As your lodash example indicates, the downside of binding to "this" is that such "virtual methods" can't really be used ergonomically without the `::` syntax.  And the `::` syntax can't be used with non-method functions.

On the other hand, in my opinion the syntactic gap we are filling here is not simply putting the first parameter on the left of the function identifier.  (That would be controversial anyway, since many "functional" programmers are just fine with right-to-left composition.)  Instead, it is providing a the user with a convenient way to express the notion of "extension methods".  And for extension methods it is natural to use "this".

In practice, I've found that using "this" feels completely natural in this context.  That could be a result of personal bias, though : )

Regarding lodash specifically, I imaging that it would be pretty easy to rewrite lodash as a library of extension methods.

**Comment by gsklee** [comment]
@aaronshaf There's nothing I can do here because this entire lib is specifically designed to be used together with the `::` bind operator. You should bring the discussion to https://github.com/zenparsing/es-function-bind instead.
